packages:
  - src/**
  - extensions/**

allowBuilds:
  '@biomejs/biome': false
  core-js: false
  esbuild: false
  msgpackr-extract: false
  sharp: false

minimumReleaseAgeExclude:
  - react-scan@0.5.7
