[package]
name = "swc_async_require_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
swc_core = { version = "0.90.0", features = ["ecma_plugin_transform"] }
wasm-bindgen = "0.2"
