# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to GitHub Pages (artifact flow)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Pages (inject basePath / outputs)
        id: configure-pages
        uses: actions/configure-pages@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          static_site_generator: 'next'
          generator_config_file: 'next.config.ts'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (no cache)
        run: npm ci

      - name: Build (production) and export to out/
        env:
          BUILD_MODE: production
          NEXT_PUBLIC_IS_PRODUCTION_BUILD: 'true'
          # configure-pages outputs base_path without trailing slash ('' for user/org site)
          NEXT_PUBLIC_BASE_PATH: ${{ steps.configure-pages.outputs.base_path }}
        run: |
          npm run build
          # next export uses the 'output: export' injected by configure-pages for Next
          npx --yes next export || true

      - name: Ensure out/ exists (debug)
        run: |
          if [ -d out ]; then
            echo "out/ exists, size:" && du -sh out || true
            ls -la out | sed -n '1,200p'
          else
            echo "Error: out/ not found" && ls -la && exit 1
          fi

      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
          name: github-pages

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy artifact to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
